name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller build_exe.spec

    - name: Get version from tag
      id: get_version
      shell: bash
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=dev-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CarousellScraper-Windows-${{ steps.get_version.outputs.VERSION }}
        path: dist/CarousellScraper.exe
        retention-days: 30

    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/CarousellScraper.exe
        draft: false
        prerelease: false
        body: |
          ## Carousell Scraper ${{ steps.get_version.outputs.VERSION }}

          ### Download
          Download `CarousellScraper.exe` below and run it on Windows.

          ### What's New
          - Automated build from GitHub Actions
          - See commit history for detailed changes

          ### Usage
          1. Download the `.exe` file
          2. Double-click to run
          3. The Streamlit interface will open in your default browser

          ### Requirements
          - Windows 10 or later
          - Chrome browser (for web scraping)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
