[server]
headless = true
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[global]
developmentMode = false
showWarningOnDirectExecution = false

[theme]
base = "light"
